version: '3'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    ports:
      - "3306:3306"
    networks:
      - myNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: raed13/backend:latest
    container_name: backend-devops
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    networks:
      - myNetwork

networks:
  myNetwork:

volumes:
  mysql-data: