version: '3'
services:
  spring-app:
    image: rihemrd/DrissiRihem_G5_SKI-STATION
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stationSki
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
