version: '3'
services:
  spring-app:
    image: rihemrd/DrissiRihem_G5_GESTION-STATION-SKI
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stationSki
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    networks:
      - myNetwork
    volumes:
      - mysql-data:/var/lib/mysql
