version: '3'
services:
  spring-app:
    image: gestion-station-ski
    ports:
      - "3306:3306"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: stationSki
