version: '3'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb  # Keep the name consistent (no spaces)
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    networks:
      - myNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: saifmessaoudi/backend-devops:latest
    container_name: springboot-app  # Clearer container naming
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    networks:
      - myNetwork
    environment:  # Optional environment variables for Spring Boot
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stationSki
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  myNetwork:  # Define the network without additional configuration if defaults are acceptable

volumes:
  mysql-data:  # No configuration is required here unless specific options are needed
