version: "3"

services:
  mysqldb:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=admin
      - MYSQL_DATABASE=stationSki
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-foyer:
    depends_on:
      - mysqldb
    image: rihemrd/DrissiRihem_G5_GESTION-STATION-SKI:latest
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: