version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=skidb

    ports:
      - "3306:3306"
    networks:
      - myNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: saifmessaoudi/backend-devops:latest
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    networks:
      - myNetwork

networks:
  myNetwork:

volumes:
  mysql-data: