version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=devops
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Consider setting a password for production
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  springboot-app:
    image: wassimns/devops:latest
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Ensure consistency with MySQL (empty password)
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - springboot-mysql-network

volumes:
  mysql_data:

networks:
  springboot-mysql-network:
    driver: bridge
