version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  springboot-app:
    image: wassimns/devops:latest
    container_name: springboot-app
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - springboot-mysql-network

volumes:
  mysql_data:

networks:
  springboot-mysql-network:
