version: '3'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql1
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    networks:
      - myNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: raed13/backend:latest
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    networks:
      - myNetwork

networks:
  myNetwork:

volumes:
  mysql-data:
